---
version: "2"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022 #optional
    volumes:
      - ./config:/config
      - $SERIES_FOLDER:/tv
      - $DOWNLOADS_FOLDER:/downloads
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=insecure"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.$DOMAIN`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
        # - "traefik.http.routers.sonarr.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
