---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK=022
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - $DOWNLOADS_FOLDER:/downloads
    # ports:
    #   - 6881:6881
    #   - 6881:6881/udp
    #   - 8080:8080
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.entrypoints=insecure"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.$DOMAIN`)"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      # - "traefik.http.routers.qbittorrent.tls.certresolver=le"

networks:
    default:
        name: $DEFAULT_NETWORK
        external: true
