---
version: "3"
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./n8n:/root/.n8n
    # ports:
    #   - 5678:5678
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entrypoints=insecure"
      - "traefik.http.routers.n8n.rule=Host(`n8n.$DOMAIN`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      # - "traefik.http.routers.n8n.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
