---
version: "2"
services:
  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
    # ports:
    #   - 80:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.piwigo.entrypoints=secure"
      - "traefik.http.routers.piwigo.rule=Host(`piwigo.$DOMAIN`)"
      - "traefik.http.services.piwigo.loadbalancer.server.port=80"
      - "traefik.http.routers.piwigo.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
