---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=$MYSQL_PASSWORD
      - DB_DATABASE=$DATABASE_NAME
      - APP_URL=$APP_URL
    volumes:
      - $DATA_FOLDER:/config
        # ports:
        #   - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.entrypoints=insecure"
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.$DOMAIN`)"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
      # - "traefik.http.routers.bookstack.tls.certresolver=le"

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - TZ=Europe/Paris
      - MYSQL_DATABASE=$DATABASE_NAME
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - $DATA_FOLDER:/config
    restart: unless-stopped

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
