version: '3'

services:
  traefik:
    image: traefik
    restart: always
    container_name: "traefik"
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # The HTTP port
      - "80:80"
      # - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      # - "./config.yml:/etc/traefik/config.yml"
      # - "./certs:/etc/certs:ro"
      # - "./acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"
      - "traefik.http.routers.traefik.tls=true"
      ## HTTP REDIRECT
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"
      # - "traefik.http.routers.redirect-https.entrypoints=insecure"
      # - "traefik.http.routers.redirect-https.middlewares=redirect-to-https"

networks:
    default:
        name: $DEFAULT_NETWORK
        external: true
