---
version: "2.1"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - $DATA_FOLDER:/data
    # ports:
    #   - 443:443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=insecure"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.$DOMAIN`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
        # - "traefik.http.routers.nextcloud.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
