---
version: "3"
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.docker.home'
    # environment:
      # GITLAB_OMNIBUS_CONFIG: |
      #   external_url 'http://gitlab.docker.home'
      #   # Add any other gitlab.rb configuration here, each on its own line
    # ports:
    #   # - 80:80
    #   # - 443:443
    #   - 22:22
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.entrypoints=insecure"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.$DOMAIN`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      # - "traefik.http.routers.gitlab.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
