---
version: "2"
services:
  dokuwiki:
    image: linuxserver/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - APP_URL=/dokuwiki #optional
    volumes:
      - ./config:/config
    ports:
      - 801:80
      # - 443:443 #optional
    restart: unless-stopped
