---
version: "2"
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      # - APP_URL=/dokuwiki #optional
    volumes:
      - ./config:/config
    # ports:
    #   - 801:80
    #   - 443:443 #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dokuwiki.entrypoints=insecure"
      - "traefik.http.routers.dokuwiki.rule=Host(`dokuwiki.$DOMAIN`)"
      - "traefik.http.services.dokuwiki.loadbalancer.server.port=80"
      # - "traefik.http.routers.dokuwiki.tls.certresolver=le"

networks:
    default:
        name: $DEFAULT_NETWORK
        external: true
