---
version: "2.1"
services:
  znc:
    image: linuxserver/znc
    container_name: znc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
    # ports:
    #   - 6501:6501
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.znc.entrypoints=insecure"
      - "traefik.http.routers.znc.rule=Host(`znc.$DOMAIN`)"
      - "traefik.http.services.znc.loadbalancer.server.port=6501"
        # - "traefik.http.routers.znc.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
