---
version: '3'
  
services:
    koillection:
        image: koillection/koillection
        container_name: koillection
        restart: unless-stopped
        ports:
            - 81:80
        env_file:
            - .env
        depends_on:
            - koillection_db
        volumes:
            - ./volumes/koillection/uploads:/uploads
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.koillection.entrypoints=insecure"
            - "traefik.http.routers.koillection.rule=Host(`koillection.$DOMAIN`)"
            - "traefik.http.services.koillection.loadbalancer.server.port=81"
            # - "traefik.http.routers.koillection.tls.certresolver=le"

    koillection_db:
        image: postgres:15
        container_name: koillection_db
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - "./volumes/postgresql:/var/lib/postgresql/data"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
