version: '2'
services:
  boinc:
    # standard x86-64
    image: boinc/client:latest
    # ARMv7 32-bit e.g. Raspberry Pi 2
    # image: boinc/client:arm32v7
    # ARMv8 64-bit e.g. Raspberry Pi 3/4
    # image: boinc/client:arm64v8
    # AMD GPU
    # image: boinc/client:amd
    container_name: boinc
    restart: always
    network_mode: host
    pid: host
    volumes:
      - /opt/appdata/boinc:/var/lib/boinc
    environment:
      - TZ=Europe/Paris
      - BOINC_GUI_RPC_PASSWORD=$BOINC_PASSWORD
      - BOINC_CMD_LINE_OPTIONS=--allow_remote_gui_rpc
    # only for AMD gpu
    # group_add:
      # - video
