---
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ./config:/config
      - $MEDIA_FOLDER:/books
    # ports:
    #   - 8083:8083
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.entrypoints=insecure"
      - "traefik.http.routers.calibre.rule=Host(`calibre.$DOMAIN`)"
      - "traefik.http.services.calibre.loadbalancer.server.port=8083"
        # - "traefik.http.routers.calibre.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
