---
version: "2"
services:
  ampache:
      image: ampache/ampache
      # image: ampache/ampache:develop # dev branch
    container_name: ampache
    volumes:
      - /path/to/music media:/media
    ports:
      - 80:80
    restart: unless-stopped
