---
version: "2"
services:
  ampache:
      image: ampache/ampache
      # image: ampache/ampache:develop # dev branch
    container_name: ampache
    volumes:
      - $MEDIA_FOLDER:/media
    # ports:
    #   - 80:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ampache.entrypoints=insecure"
      - "traefik.http.routers.ampache.rule=Host(`ampache.$DOMAIN`)"
      - "traefik.http.services.ampache.loadbalancer.server.port=80"
      # - "traefik.http.routers.ampache.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
