---
services:
  pywb:
    image: webrecorder/pywb
    container_name: pywb
    volumes:
      - ./data:/webarchive
    # ports:
    #   - 8080:8080
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pywb.entrypoints=insecure"
      - "traefik.http.routers.pywb.rule=Host(`pywb.$DOMAIN`)"
      - "traefik.http.services.pywb.loadbalancer.server.port=8080"
      # - "traefik.http.routers.jellyfin.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
