---
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
      - $DOWNLOADS_FOLDER:/downloads
    # ports:
    #   - 6789:6789
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget.entrypoints=insecure"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.$DOMAIN`)"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
      # - "traefik.http.routers.nzbget.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
