---
services:
  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - fpm="false"
      - branch="v2-master"
    volumes:
      - ./config:/config
    # ports:
    #   - 80:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr.entrypoints=insecure"
      - "traefik.http.routers.organizr.rule=Host(`organizr.$DOMAIN`)"
      - "traefik.http.services.organizr.loadbalancer.server.port=80"
      # - "traefik.http.routers.organizr.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
