version: '2'

services:
  huginn_db:
    image: postgres
    container_name: huginn_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USERNAME

  huginn:
    image: huginn/huginn
    container_name: huginn
    restart: always
    # ports:
    #   - "3000:3000"
    environment:
      - HUGINN_DATABASE_ADAPTER=postgresql
      - HUGINN_DATABASE_USERNAME=$DB_USERNAME
      - HUGINN_DATABASE_PASSWORD=$DB_PASSWORD
    depends_on:
      - huginn_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huginn.entrypoints=insecure"
      - "traefik.http.routers.huginn.rule=Host(`huginn.$DOMAIN`)"
      - "traefik.http.services.huginn.loadbalancer.server.port=3000"
        # - "traefik.http.routers.huginn.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
