---
version: '3'

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    # environment:
    # - MYSQL_ROOT_PASSWORD=
    env_file:
      - ./db.env

  app:
    image: matomo:fpm-alpine
    restart: always
    links:
      - db
    volumes:
    # - ./config:/var/www/html/config:rw
    # - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    # ports:
    # - 8080:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matomo.entrypoints=secure"
      - "traefik.http.routers.matomo.rule=Host(`matomo.$DOMAIN`)"
      - "traefik.http.services.matomo.loadbalancer.server.port=80"
      - "traefik.http.routers.matomo.tls.certresolver=le"

volumes:
  db:
  matomo:

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
