---
version: "2.1"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK=022
    volumes:
      - ./config:/config
      - $DATA_FOLDER:/data1
    ports:
    #   - 8384:8384 # webui
      - 22000:22000 # listening port
      - 21027:21027/udp # protocol discovery
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.entrypoints=insecure"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.$DOMAIN`)"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
        # - "traefik.http.routers.syncthing.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
