---
version: "3"
services:
  photoprism:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    container_name: photoprism
        # user: "1000:1000"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    # ports:
    #   - 2342:2342 # [local port]:[container port]
    # Uncomment the following lines to enable regular health checks (causes automatic restarts):
    # healthcheck:
    #   test: ["CMD", "photoprism", "status"]
    #   interval: 60s
    #   timeout: 15s
    #   retries: 5
    #
    # Run "photoprism help" and "photoprism config" too see all config options and current values:
    environment: # Run "photoprism help" and "photoprism config" too see all config options and current values
      PHOTOPRISM_ADMIN_PASSWORD: $ADMIN_PASSWORD     # Initial admin password: PLEASE CHANGE!
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enable experimental features
      PHOTOPRISM_SITE_URL: $PHOTOPRISM_URL           # Canonical / public site URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_SETTINGS_HIDDEN: "false"            # Users can not view or change settings
      PHOTOPRISM_DATABASE_DRIVER: "sqlite"           # SQLite is an embedded database that doesn't require a server
      # PHOTOPRISM_DATABASE_DRIVER: "mysql"          # Use MariaDB instead of SQLite for improved performance
      # PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      # PHOTOPRISM_DATABASE_NAME: "photoprism"
      # PHOTOPRISM_DATABASE_USER: "photoprism"
      # PHOTOPRISM_DATABASE_PASSWORD: "insecure"
      PHOTOPRISM_SIDECAR_JSON: "true"                # Automatically create JSON sidecar files using Exiftool
      PHOTOPRISM_SIDECAR_YAML: "true"                # Automatically backup metadata to YAML sidecar files
      PHOTOPRISM_THUMB_FILTER: "lanczos"             # Resample filter, best to worst: blackman, lanczos, cubic, linear
      PHOTOPRISM_THUMB_UNCACHED: "false"             # Enable on-demand thumbnail rendering (high memory and cpu usage)
      PHOTOPRISM_THUMB_SIZE: 2048                    # Pre-rendered thumbnail size limit (default 2048, min 720, max 7680)
      # PHOTOPRISM_THUMB_SIZE: 4096                  # Retina 4K, DCI 4K (requires more storage); 7680 for 8K Ultra HD
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680           # On-demand rendering size limit (default 7680, min 720, max 7680)
      PHOTOPRISM_JPEG_SIZE: 7680                     # Size limit for converted image files in pixels (720-30000)
      PHOTOPRISM_JPEG_QUALITY: 92                    # Set to 95 for high-quality thumbnails (25-100)
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Use darktable presets (disables concurrent raw to jpeg conversion)
      # You may optionally set user, group and/or file permissions using environment variables:
      # UID: 1000
      # GID: 1000
      # UMASK: 0000
    volumes:
      # Storage folder for settings, index & sidecar files (DON'T REMOVE):
      - "~/.photoprism:/photoprism/storage"
      # Your personal photo and video collection ([local path]:[container path]):
      - "~/Pictures:/photoprism/originals"
      # Multiple folders can be indexed by mounting them as subfolders of /photoprism/originals:
      # - "~/Family:/photoprism/originals/Family"    # [folder_1]:/photoprism/originals/[folder_1]
      # - "~/Friends:/photoprism/originals/Friends"  # [folder_2]:/photoprism/originals/[folder_2]
      # Mounting the import folder is optional (see docs):
      # - "~/Import:/photoprism/import"
    # Uncomment the following lines to use MariaDB instead of SQLite for improved performance & scalability:
    #
    #  mariadb:
    #    image: mariadb:10.5
    #    restart: unless-stopped
    #    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    #    volumes:
    #      - "/var/lib/mysql"
    #    environment:
    #      MYSQL_ROOT_PASSWORD: please-change
    #      MYSQL_USER: photoprism
    #      MYSQL_PASSWORD: insecure
    #      MYSQL_DATABASE: photoprism

    # Uncomment the following lines to upgrade automatically, whenever there is a new Docker image available:
    #
    #  watchtower:
    #    image: containrrr/watchtower
    #    restart: unless-stopped
    #    volumes:
    #      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photoprism.entrypoints=insecure"
      - "traefik.http.routers.photoprism.rule=Host(`photoprism.$DOMAIN`)"
      - "traefik.http.services.photoprism.loadbalancer.server.port=2342"
      # - "traefik.http.routers.photoprism.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
