---
services:
  jamulus:
    image: grundic/jamulus
    container_name: jamulus
    environment:
      TZ: "Europe/Paris"  
    ports:
      - 22124:22124/udp
    restart: unless-stopped
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--welcomemessage"
      - "Welcome to David B's room"
      - "--numchannels"
      - "16"
      - "--multithreading"
      - "--fastupdate"
